### ISSUE TITLE
Getting Started link on Documentation page broken.

### ISSUE THREAD

**Issue by cargilltay** [yarnpkg/website#420] opened 2017-03-21 11:34 UTC
The Getting Started link on https://yarnpkg.com/en/docs linked to:
https://yarnpkg.com/en/docs/getting-started

Should link to:
https://yarnpkg.com/lang/en/docs/getting-started/

**Comment by Haroenv** [comment] 2017-03-21 11:43
I don't think it should, everywhere it should link to /en directly

**Comment by michielbdejong** [comment] 2017-03-21 12:03
Well, https://yarnpkg.com/lang/en/docs/getting-started/ works and https://yarnpkg.com/en/docs/getting-started is a 404.

**Comment by michielbdejong** [comment] 2017-03-21 12:10
The same issue happens on the link from https://yarnpkg.com/en/docs/creating-a-project to https://yarnpkg.com/ [lang/] en/docs/managing-dependencies/.

Notice that in both cases, the linking page does not have `lang/` in the url, but the linked-to one does.

**Comment by Haroenv** [comment] 2017-03-21 12:23
The issue is just that no trailing slash doesn't work I think. That's happening because of the rewrites (see _redirects and https://www.netlify.com/docs/redirects/)

**Comment by michielbdejong** [comment] 2017-03-21 12:36
ok, but shouldn't both 404s still be fixed, you think?

**Comment by Haroenv** [comment] 2017-03-21 12:46
Definitely

**Comment by Bshally** [comment] 2017-03-21 13:57
[Home page](https://yarnpkg.com/en/) is 404'ing at the moment. 
![screen shot 2017-03-21 at 9 57 22 am](https://cloud.githubusercontent.com/assets/3440317/24150685/d2727faa-0e1c-11e7-8379-3d2f610e43eb.png)

**Comment by Daniel15** [comment] 2017-03-21 16:59
This is strange, because the non-English languages are working fine:

https://yarnpkg.com/pt-BR/
https://yarnpkg.com/pt-BR/docs/getting-started/

**Comment by spencer-brown** [comment] 2017-03-22 00:28
The main link to the CLI docs is also broken per my comment here: https://github.com/yarnpkg/website/issues/422#issuecomment-288238540

**Comment by Haroenv** [comment] 2017-03-23 10:19
I think the 404ing is completely fixed now, but the content doesn't seem to be up to date with the last few PRs. Is the deploy fixed on Netlify or something?

**Closed** 2017-03-27 19:09 UTC
