### ISSUE TITLE
In documentation of installation section, download link is invalid! 

### ISSUE THREAD

**Issue by SUCHITRAGIRI** [yarnpkg/website#1144] opened 2022-01-05 15:00 UTC
![Screenshot (552)_LI](https://user-images.githubusercontent.com/60110218/148238662-66274015-7845-4b30-ae48-cfc2c0d67919.jpg)

Here I am attaching the snapshot, and the link of this page is https://classic.yarnpkg.com/lang/en/docs/install/#windows-stable.

Kindly resolve the issue!

**Comment by Haroenv** [comment] 2022-01-05 15:51
Not sure why the latest version isn't available, but the latest which is available is here: https://github.com/yarnpkg/yarn/releases/tag/v1.22.15

cc @Daniel15

**Comment by Haroenv** [comment] 2022-01-05 15:52
this might be a duplicate of https://github.com/yarnpkg/yarn/issues/8750 and https://github.com/yarnpkg/yarn/issues/8618

**Comment by Daniel15** [comment] 2024-05-24 22:33
Closing old issue. I think this was fixed a while back.

**Closed by Daniel15** 2024-05-24 22:33 UTC
